export const POST_TASK_REQ = "POST_TASK_REQ"
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS"
export const POST_TASK_FAILURE = "POST_TASK_FAILURE"

export const GET_TASKS_REQ = "GET_TASKS_REQ"
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS"
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE"

export const EDIT_TASK_REQ = "EDIT_TASK_REQ"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE"

export const ADD_SUBTASK_REQ = "ADD_SUBTASK_REQ"
export const ADD_SUBTASK_SUCCESS = "ADD_SUBTASK_SUCCESS"
export const ADD_SUBTASK_FAILURE = "ADD_SUBTASK_FAILURE"


export const TOGGLE_SUBTASK_REQ = "TOGGLE_SUBTASK_REQ"
export const TOGGLE_SUBTASK_SUCCESS = "TOGGLE_SUBTASK_SUCCESS"
export const TOGGLE_SUBTASK_FAILURE = "TOGGLE_SUBTASK_FAILURE"

